name: module3_task2
on:
  schedule:
    - cron: "0 0 * * *"
  push:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - working-directory: module3_task2
        run: ./setup.sh
      - working-directory: module3_task2
        run: make help
      - name: BuildMe
        working-directory: module3_task2
        run: make build
      - name: CreatePost
        working-directory: module3_task2
        run: make POST_NAME=welcome_again POST_TITLE="Welcome again" post
      - name: Package
        working-directory: module3_task2
        run: make package
      - name: LINT
        working-directory: module3_task2
        run: make lint
      - name: unit-test
        working-directory: module3_task2
        run: make unit-tests
      - name: ntegration-tests
        working-directory: module3_task2
        run: make integration-tests
      - name: validate
        working-directory: module3_task2
        run: make validate
      - name: Save workflow
        uses: actions/upload-artifact@v3
        with:
          name: artifact-task2
          path: module3_task2/
